// questions.js
// Data structure: [unit, [parts], [correct], explanation_string]
// format: "Concrete Japanese Prompt (Grammar/Hint)"

const RAW_DATA = [
    // --- JHS 1: Be Verbs (be) ---
    ["jhs1_be", ["I", "am", "a", "student", "."], "I am a student .", "私は学生です (I am ～)"],
    ["jhs1_be", ["You", "are", "a", "teacher", "."], "You are a teacher .", "あなたは先生です (You are ～)"],
    ["jhs1_be", ["He", "is", "a", "doctor", "."], "He is a doctor .", "彼は医者です (He is ～)"],
    ["jhs1_be", ["You", "are", "my", "friend", "."], "You are my friend .", "あなたは私の友達です (You are ～)"],
    ["jhs1_be", ["She", "is", "my", "sister", "."], "She is my sister .", "彼女は私の姉妹です (She is ～)"],
    ["jhs1_be", ["This", "is", "my", "dog", "."], "This is my dog .", "これは私の犬です (This is ～)"],
    ["jhs1_be", ["He", "is", "a", "teacher", "."], "He is a teacher .", "彼は先生です (He is ～)"],
    ["jhs1_be", ["She", "is", "a", "singer", "."], "She is a singer .", "彼女は歌手です (She is ～)"],
    ["jhs1_be", ["Ken", "is", "my", "brother", "."], "Ken is my brother .", "ケンは私の兄弟です (Ken is ～)"],
    ["jhs1_be", ["She", "is", "from", "Canada", "."], "She is from Canada .", "彼女はカナダ出身です (She is ～)"],
    ["jhs1_be", ["I", "am", "from", "Japan", "."], "I am from Japan .", "私は日本出身です (I am ～)"],
    ["jhs1_be", ["He", "is", "from", "America", "."], "He is from America .", "彼はアメリカ出身です (He is ～)"],
    ["jhs1_be", ["It", "is", "a", "dog", "."], "It is a dog .", "それは犬です (It is ～)"],
    ["jhs1_be", ["It", "is", "an", "apple", "."], "It is an apple .", "それはリンゴです (It is ～)"],
    ["jhs1_be", ["That", "is", "a", "bird", "."], "That is a bird .", "あれは鳥です (That is ～)"],
    ["jhs1_be", ["This", "is", "my", "pen", "."], "This is my pen .", "これは私のペンです (This is ～)"],
    ["jhs1_be", ["That", "is", "your", "bag", "."], "That is your bag .", "あれはあなたの鞄です (That is ～)"],
    ["jhs1_be", ["This", "is", "her", "book", "."], "This is her book .", "これは彼女の本です (This is ～)"],
    ["jhs1_be", ["Are", "you", "hungry", "?"], "Are you hungry ?", "あなたはお腹が空いていますか (Are you ～?)"],
    ["jhs1_be", ["Are", "you", "tired", "?"], "Are you tired ?", "あなたは疲れていますか (Are you ～?)"],
    ["jhs1_be", ["Are", "you", "happy", "?"], "Are you happy ?", "あなたは幸せですか (Are you ～?)"],
    ["jhs1_be", ["Is", "he", "busy", "?"], "Is he busy ?", "彼は忙しいですか (Is he ～?)"],
    ["jhs1_be", ["Is", "Ken", "free", "?"], "Is Ken free ?", "ケンは暇ですか (Is Ken ～?)"],
    ["jhs1_be", ["Is", "she", "kind", "?"], "Is she kind ?", "彼女は親切ですか (Is she ～?)"],
    ["jhs1_be", ["Is", "that", "true", "?"], "Is that true ?", "それは本当ですか (Is that ～?)"],
    ["jhs1_be", ["Are", "they", "happy", "?"], "Are they happy ?", "彼らは幸せですか (Are they ～?)"],
    ["jhs1_be", ["Are", "we", "ready", "?"], "Are we ready ?", "私たちは準備できていますか (Are we ～?)"],
    ["jhs1_be", ["I", "am", "not", "tired", "."], "I am not tired .", "私は疲れていません (I am not ～)"],
    ["jhs1_be", ["I", "am", "not", "busy", "."], "I am not busy .", "私は忙しくありません (I am not ～)"],
    ["jhs1_be", ["You", "are", "not", "old", "."], "You are not old .", "あなたは年をとっていません (You are not ～)"],
    ["jhs1_be", ["He", "is", "not", "Japanese", "."], "He is not Japanese .", "彼は日本人ではありません (is not)"],
    ["jhs1_be", ["She", "is", "not", "a", "student", "."], "She is not a student .", "彼女は学生ではありません (is not)"],
    ["jhs1_be", ["We", "are", "students", "."], "We are students .", "私たちは学生です (We are ～)"],
    ["jhs1_be", ["We", "are", "friends", "."], "We are friends .", "私たちは友達です (We are ～)"],
    ["jhs1_be", ["They", "are", "flowers", "."], "They are flowers .", "それらは花です (They are ～)"],
    ["jhs1_be", ["Who", "is", "that", "boy", "?"], "Who is that boy ?", "あの少年は誰ですか (Who is ～?)"],
    ["jhs1_be", ["Who", "is", "that", "girl", "?"], "Who is that girl ?", "あの少女は誰ですか (Who is ～?)"],
    ["jhs1_be", ["Who", "is", "this", "man", "?"], "Who is this man ?", "この男性は誰ですか (Who is ～?)"],
    ["jhs1_be", ["What", "is", "this", "?"], "What is this ?", "これは何ですか (What is ～?)"],
    ["jhs1_be", ["What", "is", "that", "?"], "What is that ?", "あれは何ですか (What is ～?)"],
    ["jhs1_be", ["Where", "is", "the", "park", "?"], "Where is the park ?", "公園はどこですか (Where is ～?)"],
    ["jhs1_be", ["Where", "is", "the", "station", "?"], "Where is the station ?", "駅はどこですか (Where is ～?)"],
    ["jhs1_be", ["How", "is", "the", "weather", "?"], "How is the weather ?", "天気はどうですか (How is ～?)"],
    ["jhs1_be", ["How", "is", "your", "father", "?"], "How is your father ?", "あなたのお父さんは元気ですか (How is ～?)"],
    ["jhs1_be", ["My", "name", "is", "Yumi", "."], "My name is Yumi .", "私の名前はユミです (My name is ～)"],
    ["jhs1_be", ["Her", "mother", "is", "a", "doctor", "."], "Her mother is a doctor .", "彼女の母は医者です (Her mother is ～)"],
    ["jhs1_be", ["The", "sky", "is", "blue", "."], "The sky is blue .", "空は青いです (The sky is ～)"],
    ["jhs1_be", ["These", "are", "my", "books", "."], "These are my books .", "これらは私の本です"],
    ["jhs1_be", ["Those", "are", "birds", "."], "Those are birds .", "あれらは鳥です"],

    // --- JHS 1: General Verbs (general) ---
    ["jhs1_general", ["I", "play", "tennis", "."], "I play tennis .", "私はテニスをします"],
    ["jhs1_general", ["I", "play", "soccer", "."], "I play soccer .", "私はサッカーをします"],
    ["jhs1_general", ["We", "play", "baseball", "."], "We play baseball .", "私たちは野球をします"],
    ["jhs1_general", ["You", "like", "music", "."], "You like music .", "あなたは音楽が好きです"],
    ["jhs1_general", ["I", "like", "dogs", "."], "I like dogs .", "私は犬が好きです"],
    ["jhs1_general", ["They", "like", "cats", "."], "They like cats .", "彼らは猫が好きです"],
    ["jhs1_general", ["We", "study", "English", "."], "We study English .", "私たちは英語を勉強します"],
    ["jhs1_general", ["You", "study", "math", "."], "You study math .", "あなたは数学を勉強します"],
    ["jhs1_general", ["They", "run", "fast", "."], "They run fast .", "彼らは速く走ります"],
    ["jhs1_general", ["I", "run", "fast", "."], "I run fast .", "私は速く走ります"],
    ["jhs1_general", ["I", "have", "a", "sister", "."], "I have a sister .", "私には姉がいます"],
    ["jhs1_general", ["I", "have", "a", "brother", "."], "I have a brother .", "私には兄がいます"],
    ["jhs1_general", ["You", "have", "a", "pen", "."], "You have a pen .", "あなたはペンを持っています"],
    ["jhs1_general", ["Do", "you", "know", "him", "?"], "Do you know him ?", "あなたは彼を知っていますか (Do you ～?)"],
    ["jhs1_general", ["Do", "you", "know", "her", "?"], "Do you know her ?", "あなたは彼女を知っていますか (Do you ～?)"],
    ["jhs1_general", ["Do", "they", "play", "soccer", "?"], "Do they play soccer ?", "彼らはサッカーをしますか (Do they ～?)"],
    ["jhs1_general", ["Do", "we", "have", "time", "?"], "Do we have time ?", "私たちに時間はありますか (Do we ～?)"],
    ["jhs1_general", ["I", "do", "not", "eat", "natto", "."], "I do not eat natto .", "私は納豆を食べません (do not)"],
    ["jhs1_general", ["I", "do", "not", "like", "snakes", "."], "I do not like snakes .", "私はヘビが好きではありません (do not)"],
    ["jhs1_general", ["You", "do", "not", "need", "it", "."], "You do not need it .", "あなたにはそれが必要ありません"],
    ["jhs1_general", ["He", "plays", "the", "piano", "."], "He plays the piano .", "彼はピアノを弾きます (plays)"],
    ["jhs1_general", ["My", "father", "plays", "golf", "."], "My father plays golf .", "私の父はゴルフをします (plays)"],
    ["jhs1_general", ["She", "goes", "to", "school", "."], "She goes to school .", "彼女は学校へ行きます (goes)"],
    ["jhs1_general", ["He", "goes", "to", "work", "."], "He goes to work .", "彼は仕事に行きます (goes)"],
    ["jhs1_general", ["It", "looks", "nice", "."], "It looks nice .", "それは素敵に見えます (looks)"],
    ["jhs1_general", ["The", "food", "looks", "good", "."], "The food looks good .", "その食べ物は美味しそうです (looks)"],
    ["jhs1_general", ["Ken", "studies", "math", "."], "Ken studies math .", "ケンは数学を勉強します (studies)"],
    ["jhs1_general", ["Does", "he", "like", "dogs", "?"], "Does he like dogs ?", "彼は犬が好きですか (Does he ～?)"],
    ["jhs1_general", ["Does", "Tom", "play", "tennis", "?"], "Does Tom play tennis ?", "トムはテニスをしますか (Does Tom ～?)"],
    ["jhs1_general", ["Does", "she", "speak", "French", "?"], "Does she speak French ?", "彼女はフランス語を話しますか (Does she ～?)"],
    ["jhs1_general", ["He", "does", "not", "swim", "."], "He does not swim .", "彼は泳ぎません (does not)"],
    ["jhs1_general", ["She", "does", "not", "know", "me", "."], "She does not know me .", "彼女は私を知りません (does not)"],
    ["jhs1_general", ["She", "does", "not", "have", "time", "."], "She does not have time .", "彼女には時間がありません"],
    ["jhs1_general", ["Who", "plays", "games", "?"], "Who plays games ?", "誰がゲームをしますか (Who plays ～?)"],
    ["jhs1_general", ["Who", "wants", "ice", "cream", "?"], "Who wants ice cream ?", "誰がアイスクリームを欲しいですか (Who wants ～?)"],
    ["jhs1_general", ["What", "do", "you", "want", "?"], "What do you want ?", "あなたは何が欲しいですか"],
    ["jhs1_general", ["What", "does", "he", "study", "?"], "What does he study ?", "彼は何を勉強しますか"],
    ["jhs1_general", ["When", "do", "you", "get", "up", "?"], "When do you get up ?", "あなたはいつ起きますか"],
    ["jhs1_general", ["When", "does", "school", "start", "?"], "When does school start ?", "学校はいつ始まりますか"],
    ["jhs1_general", ["Where", "does", "he", "live", "?"], "Where does he live ?", "彼はどこに住んでいますか"],

    // --- JHS 1: Can (can) ---
    ["jhs1_can", ["I", "can", "swim", "."], "I can swim .", "私は泳ぐことができます (can)"],
    ["jhs1_can", ["I", "can", "cook", "."], "I can cook .", "私は料理ができます (can)"],
    ["jhs1_can", ["You", "can", "use", "my", "pen", "."], "You can use my pen .", "あなたは私のペンを使ってもよいです (can)"],
    ["jhs1_can", ["You", "can", "eat", "this", "."], "You can eat this .", "あなたはこれを食べてもよいです (can)"],
    ["jhs1_can", ["He", "can", "run", "fast", "."], "He can run fast .", "彼は速く走れます (can)"],
    ["jhs1_can", ["She", "can", "speak", "English", "."], "She can speak English .", "彼女は英語を話せます (can)"],
    ["jhs1_can", ["Can", "you", "help", "me", "?"], "Can you help me ?", "私を手伝ってくれますか (Can you ～?)"],
    ["jhs1_can", ["Can", "you", "play", "the", "guitar", "?"], "Can you play the guitar ?", "あなたはギターを弾けますか (Can you ～?)"],
    ["jhs1_can", ["Can", "I", "open", "the", "window", "?"], "Can I open the window ?", "窓を開けてもいいですか (Can I ～?)"],
    ["jhs1_can", ["Can", "I", "use", "your", "phone", "?"], "Can I use your phone ?", "あなたの電話を使ってもいいですか (Can I ～?)"],
    ["jhs1_can", ["I", "cannot", "sing", "well", "."], "I cannot sing well .", "私は上手に歌えません (cannot)"],
    ["jhs1_can", ["I", "cannot", "drive", "."], "I cannot drive .", "私は運転できません (cannot)"],
    ["jhs1_can", ["He", "cannot", "come", "today", "."], "He cannot come today .", "彼は今日来られません"],

    // --- JHS 1: Progressive (prog) ---
    ["jhs1_prog", ["I", "am", "reading", "a", "book", "."], "I am reading a book .", "私は本を読んでいます (be + ing)"],
    ["jhs1_prog", ["I", "am", "writing", "a", "letter", "."], "I am writing a letter .", "私は手紙を書いています (be + ing)"],
    ["jhs1_prog", ["You", "are", "watching", "TV", "."], "You are watching TV .", "あなたはテレビを見ています (be + ing)"],
    ["jhs1_prog", ["We", "are", "eating", "lunch", "."], "We are eating lunch .", "私たちは昼食を食べています (be + ing)"],
    ["jhs1_prog", ["He", "is", "playing", "soccer", "."], "He is playing soccer .", "彼はサッカーをしています (be + ing)"],
    ["jhs1_prog", ["He", "is", "running", "now", "."], "He is running now .", "彼は今走っています (be + ing)"],
    ["jhs1_prog", ["She", "is", "sleeping", "now", "."], "She is sleeping now .", "彼女は今寝ています (be + ing)"],
    ["jhs1_prog", ["The", "baby", "is", "crying", "."], "The baby is crying .", "赤ちゃんが泣いています (be + ing)"],
    ["jhs1_prog", ["Are", "you", "studying", "?"], "Are you studying ?", "あなたは勉強していますか (Are you ～?)"],
    ["jhs1_prog", ["Are", "they", "working", "?"], "Are they working ?", "彼らは働いていますか (Are they ～?)"],
    ["jhs1_prog", ["What", "are", "you", "doing", "?"], "What are you doing ?", "あなたは何をしているのですか (What are you ～?)"],
    ["jhs1_prog", ["He", "is", "not", "eating", "."], "He is not eating .", "彼は食べていません (is not ～ing)"],

    // --- JHS 1: Past (past) ---
    ["jhs1_past", ["I", "played", "tennis", "yesterday", "."], "I played tennis yesterday .", "私は昨日テニスをしました (past)"],
    ["jhs1_past", ["We", "played", "games", "."], "We played games .", "私たちはゲームをしました (past)"],
    ["jhs1_past", ["He", "watched", "TV", "last", "night", "."], "He watched TV last night .", "彼は昨夜テレビを見ました (past)"],
    ["jhs1_past", ["She", "cooked", "dinner", "."], "She cooked dinner .", "彼女は夕食を作りました (past)"],
    ["jhs1_past", ["I", "went", "to", "the", "park", "."], "I went to the park .", "私は公園へ行きました (went)"],
    ["jhs1_past", ["We", "went", "shopping", "."], "We went shopping .", "私たちは買い物に行きました (went)"],
    ["jhs1_past", ["She", "came", "home", "early", "."], "She came home early .", "彼女は早く帰宅しました (came)"],
    ["jhs1_past", ["He", "came", "to", "school", "."], "He came to school .", "彼は学校に来ました (came)"],
    ["jhs1_past", ["We", "saw", "a", "movie", "."], "We saw a movie .", "私たちは映画を見ました (saw)"],
    ["jhs1_past", ["I", "saw", "a", "bird", "."], "I saw a bird .", "私は鳥を見ました (saw)"],
    ["jhs1_past", ["Did", "you", "enjoy", "the", "party", "?"], "Did you enjoy the party ?", "パーティーは楽しかったですか (Did you ～?)"],
    ["jhs1_past", ["Did", "he", "finish", "his", "homework", "?"], "Did he finish his homework ?", "彼は宿題を終えましたか (Did he ～?)"],
    ["jhs1_past", ["I", "did", "not", "know", "that", "."], "I did not know that .", "私はそれを知りませんでした (didn't)"],
    ["jhs1_past", ["She", "did", "not", "come", "."], "She did not come .", "彼女は来ませんでした (didn't)"],
    ["jhs1_past", ["Where", "did", "you", "go", "?"], "Where did you go ?", "あなたはどこに行きましたか"],
    ["jhs1_past", ["What", "did", "you", "eat", "?"], "What did you eat ?", "あなたは何を食べましたか"],

    // --- JHS 2: Future (future) ---
    ["jhs2_future", ["I", "will", "call", "you", "."], "I will call you .", "私はあなたに電話します (will)"],
    ["jhs2_future", ["I", "will", "help", "you", "."], "I will help you .", "私はあなたを手伝います (will)"],
    ["jhs2_future", ["It", "will", "rain", "tomorrow", "."], "It will rain tomorrow .", "明日は雨が降るでしょう (will)"],
    ["jhs2_future", ["It", "will", "be", "sunny", "."], "It will be sunny .", "晴れるでしょう (will)"],
    ["jhs2_future", ["I", "am", "going", "to", "study", "."], "I am going to study .", "私は勉強するつもりです (be going to)"],
    ["jhs2_future", ["He", "is", "going", "to", "buy", "a", "car", "."], "He is going to buy a car .", "彼は車を買う予定です (be going to)"],
    ["jhs2_future", ["Are", "you", "going", "to", "visit", "him", "?"], "Are you going to visit him ?", "彼を訪ねる予定ですか (Are you going to ～?)"],
    ["jhs2_future", ["Is", "she", "going", "to", "cook", "?"], "Is she going to cook ?", "彼女は料理をする予定ですか (Is she going to ～?)"],
    ["jhs2_future", ["Will", "you", "help", "me", "?"], "Will you help me ?", "手伝ってくれませんか (Will you ～?)"],
    ["jhs2_future", ["Will", "you", "open", "the", "door", "?"], "Will you open the door ?", "ドアを開けてくれませんか (Will you ～?)"],
    ["jhs2_future", ["I", "won't", "be", "late", "."], "I won't be late .", "私は遅刻しません (won't)"],
    ["jhs2_future", ["He", "won't", "go", "there", "."], "He won't go there .", "彼はそこへは行かないでしょう (won't)"],

    // --- JHS 2: Auxiliaries (aux) ---
    ["jhs2_aux", ["You", "must", "go", "now", "."], "You must go now .", "あなたは今行かなければなりません (must)"],
    ["jhs2_aux", ["We", "must", "study", "hard", "."], "We must study hard .", "私たちは一生懸命勉強しなければなりません (must)"],
    ["jhs2_aux", ["I", "have", "to", "get", "up", "."], "I have to get up .", "私は起きなければなりません (have to)"],
    ["jhs2_aux", ["She", "has", "to", "clean", "her", "room", "."], "She has to clean her room .", "彼女は部屋を掃除しなければなりません (has to)"],
    ["jhs2_aux", ["You", "should", "eat", "vegetables", "."], "You should eat vegetables .", "あなたは野菜を食べるべきです (should)"],
    ["jhs2_aux", ["He", "should", "study", "more", "."], "He should study more .", "彼はもっと勉強すべきです (should)"],
    ["jhs2_aux", ["May", "I", "come", "in", "?"], "May I come in ?", "入ってもいいですか (May I ～?)"],
    ["jhs2_aux", ["May", "I", "sit", "here", "?"], "May I sit here ?", "ここに座ってもいいですか (May I ～?)"],
    ["jhs2_aux", ["Could", "you", "open", "the", "door", "?"], "Could you open the door ?", "ドアを開けていただけませんか (Could you ～?)"],
    ["jhs2_aux", ["Could", "you", "tell", "me", "the", "way", "?"], "Could you tell me the way ?", "道を教えていただけませんか (Could you ～?)"],
    ["jhs2_aux", ["Shall", "we", "dance", "?"], "Shall we dance ?", "踊りましょうか (Shall we ～?)"],
    ["jhs2_aux", ["Shall", "we", "go", "home", "?"], "Shall we go home ?", "帰りましょうか (Shall we ～?)"],

    // --- JHS 2: Infinitive/Gerund (inf) ---
    ["jhs2_inf", ["I", "like", "to", "swim", "."], "I like to swim .", "私は泳ぐことが好きです (to swim)"],
    ["jhs2_inf", ["He", "wants", "to", "be", "a", "doctor", "."], "He wants to be a doctor .", "彼は医者になりたいです (wants to be)"],
    ["jhs2_inf", ["To", "study", "English", "is", "fun", "."], "To study English is fun .", "英語を勉強することは楽しいです"],
    ["jhs2_inf", ["To", "play", "games", "is", "exciting", "."], "To play games is exciting .", "ゲームをすることはワクワクします"],
    ["jhs2_inf", ["I", "went", "there", "to", "see", "him", "."], "I went there to see him .", "私は彼に会うためにそこへ行きました"],
    ["jhs2_inf", ["She", "got", "up", "early", "to", "run", "."], "She got up early to run .", "彼女は走るために早く起きました"],
    ["jhs2_inf", ["I", "am", "glad", "to", "meet", "you", "."], "I am glad to meet you .", "あなたに会えてうれしいです"],
    ["jhs2_inf", ["She", "was", "sad", "to", "hear", "the", "news", "."], "She was sad to hear the news .", "彼女はその知らせを聞いて悲しかった"],
    ["jhs2_inf", ["I", "have", "a", "book", "to", "read", "."], "I have a book to read .", "私には読むべき本があります"],
    ["jhs2_inf", ["I", "want", "something", "to", "drink", "."], "I want something to drink .", "私は何か飲み物が欲しい"],
    ["jhs2_inf", ["I", "enjoyed", "playing", "tennis", "."], "I enjoyed playing tennis .", "私はテニスをして楽しみました (playing)"],
    ["jhs2_inf", ["We", "finished", "eating", "lunch", "."], "We finished eating lunch .", "私たちは昼食を食べ終わりました"],
    ["jhs2_inf", ["Stop", "talking", "."], "Stop talking .", "話すのをやめなさい"],
    ["jhs2_inf", ["Start", "running", "."], "Start running .", "走り始めなさい"],
    ["jhs2_inf", ["He", "is", "good", "at", "cooking", "."], "He is good at cooking .", "彼は料理が得意です (good at)"],
    ["jhs2_inf", ["She", "is", "good", "at", "singing", "."], "She is good at singing .", "彼女は歌うのが得意です (good at)"],

    // --- JHS 2: Comparison (comp) ---
    ["jhs2_comp", ["I", "am", "taller", "than", "you", "."], "I am taller than you .", "私はあなたより背が高いです (taller than)"],
    ["jhs2_comp", ["This", "is", "bigger", "than", "that", "."], "This is bigger than that .", "これはあれより大きいです"],
    ["jhs2_comp", ["Run", "faster", "."], "Run faster .", "もっと速く走りなさい"],
    ["jhs2_comp", ["Speak", "louder", "."], "Speak louder .", "もっと大きな声で話しなさい"],
    ["jhs2_comp", ["He", "is", "the", "tallest", "."], "He is the tallest .", "彼は最も背が高いです (the tallest)"],
    ["jhs2_comp", ["Whale", "is", "the", "biggest", "animal", "."], "Whale is the biggest animal .", "クジラは最も大きな動物です"],
    ["jhs2_comp", ["This", "is", "the", "best", "movie", "."], "This is the best movie .", "これは最高の映画です"],
    ["jhs2_comp", ["He", "is", "my", "best", "friend", "."], "He is my best friend .", "彼は私の親友です"],
    ["jhs2_comp", ["Playing", "soccer", "is", "more", "exciting", "."], "Playing soccer is more exciting .", "サッカーをすることはよりワクワクします (more exciting)"],
    ["jhs2_comp", ["English", "is", "more", "interesting", "than", "math", "."], "English is more interesting than math .", "英語は数学より面白いです"],
    ["jhs2_comp", ["This", "is", "the", "most", "important", "."], "This is the most important .", "これは最も重要です (the most important)"],
    ["jhs2_comp", ["She", "is", "the", "most", "famous", "singer", "."], "She is the most famous singer .", "彼女は最も有名な歌手です"],
    ["jhs2_comp", ["I", "am", "as", "old", "as", "you", "."], "I am as old as you .", "私はあなたと同じくらいの年齢です (as ～ as)"],
    ["jhs2_comp", ["He", "can", "run", "as", "fast", "as", "Ken", "."], "He can run as fast as Ken .", "彼はケンと同じくらい速く走れます"],

    // --- JHS 2: Passive (passive) ---
    ["jhs2_passive", ["This", "car", "was", "made", "in", "Japan", "."], "This car was made in Japan .", "この車は日本で作られました (was made)"],
    ["jhs2_passive", ["The", "book", "was", "written", "by", "him", "."], "The book was written by him .", "その本は彼によって書かれました"],
    ["jhs2_passive", ["English", "is", "spoken", "by", "many", "people", "."], "English is spoken by many people .", "英語は多くの人に話されています (is spoken)"],
    ["jhs2_passive", ["Rice", "is", "eaten", "in", "Japan", "."], "Rice is eaten in Japan .", "日本ではお米が食べられています"],
    ["jhs2_passive", ["The", "letter", "was", "sent", "yesterday", "."], "The letter was sent yesterday .", "その手紙は昨日送られました"],
    ["jhs2_passive", ["The", "room", "was", "cleaned", "by", "her", "."], "The room was cleaned by her .", "その部屋は彼女によって掃除されました"],
    ["jhs2_passive", ["Is", "French", "spoken", "here", "?"], "Is French spoken here ?", "ここではフランス語が話されていますか"],
    ["jhs2_passive", ["Is", "this", "room", "used", "?"], "Is this room used ?", "この部屋は使われていますか"],

    // --- JHS 3: Perfect (perfect) ---
    ["jhs3_perfect", ["I", "have", "lost", "my", "key", "."], "I have lost my key .", "私は鍵をなくしてしまいました (have lost)"],
    ["jhs3_perfect", ["She", "has", "gone", "to", "China", "."], "She has gone to China .", "彼女は中国へ行ってしまいました"],
    ["jhs3_perfect", ["I", "have", "finished", "lunch", "."], "I have finished lunch .", "私はもう昼食を終えました (have finished)"],
    ["jhs3_perfect", ["Have", "you", "done", "your", "homework", "yet", "?"], "Have you done your homework yet ?", "もう宿題は終わりましたか"],
    ["jhs3_perfect", ["Have", "you", "ever", "seen", "this", "movie", "?"], "Have you ever seen this movie ?", "あなたはこの映画を見たことがありますか (Have you seen ～?)"],
    ["jhs3_perfect", ["Have", "you", "ever", "been", "to", "Kyoto", "?"], "Have you ever been to Kyoto ?", "京都に行ったことがありますか"],
    ["jhs3_perfect", ["I", "have", "never", "been", "there", "."], "I have never been there .", "私は一度もそこへ行ったことがありません (never been)"],
    ["jhs3_perfect", ["I", "have", "never", "seen", "a", "ghost", "."], "I have never seen a ghost .", "私は幽霊を見たことがありません"],
    ["jhs3_perfect", ["I", "have", "lived", "here", "for", "ten", "years", "."], "I have lived here for ten years .", "私はここに10年間住んでいます (have lived)"],
    ["jhs3_perfect", ["We", "have", "known", "each", "other", "since", "2010", "."], "We have known each other since 2010 .", "私たちは2010年から知り合いです"],
    ["jhs3_perfect", ["How", "long", "have", "you", "waited", "?"], "How long have you waited ?", "あなたはどのくらい待ちましたか (How long ～?)"],
    ["jhs3_perfect", ["How", "long", "have", "you", "studied", "English", "?"], "How long have you studied English ?", "どのくらい英語を勉強していますか"],

    // --- JHS 3: Participle (participle) ---
    ["jhs3_participle", ["The", "boy", "running", "over", "there", "is", "Ken", "."], "The boy running over there is Ken .", "あそこで走っている少年はケンです (running ...)"],
    ["jhs3_participle", ["The", "girl", "singing", "on", "the", "stage", "is", "my", "sister", "."], "The girl singing on the stage is my sister .", "ステージで歌っている少女は私の妹です"],
    ["jhs3_participle", ["Do", "you", "know", "the", "girl", "talking", "to", "Tom", "?"], "Do you know the girl talking to Tom ?", "トムと話している女の子を知っていますか (talking ...)"],
    ["jhs3_participle", ["Look", "at", "the", "sleeping", "cat", "."], "Look at the sleeping cat .", "眠っている猫を見て"],
    ["jhs3_participle", ["This", "is", "a", "picture", "drawn", "by", "Picasso", "."], "This is a picture drawn by Picasso .", "これはピカソによって描かれた絵です (drawn by)"],
    ["jhs3_participle", ["This", "is", "a", "cake", "made", "by", "her", "."], "This is a cake made by her .", "これは彼女によって作られたケーキです"],
    ["jhs3_participle", ["I", "have", "a", "book", "written", "in", "English", "."], "I have a book written in English .", "私は英語で書かれた本を持っています (written in)"],
    ["jhs3_participle", ["Do", "you", "have", "a", "camera", "made", "in", "Japan", "?"], "Do you have a camera made in Japan ?", "日本製のカメラを持っていますか"],

    // --- JHS 3: Relative (relative) ---
    ["jhs3_relative", ["I", "know", "the", "girl", "who", "plays", "tennis", "."], "I know the girl who plays tennis .", "私はテニスをする女の子を知っています (who)"],
    ["jhs3_relative", ["I", "have", "a", "friend", "who", "lives", "in", "Tokyo", "."], "I have a friend who lives in Tokyo .", "私には東京に住んでいる友達がいます"],
    ["jhs3_relative", ["The", "man", "who", "is", "standing", "there", "is", "my", "uncle", "."], "The man who is standing there is my uncle .", "あそこで立っている男性はわたしのおじです"],
    ["jhs3_relative", ["The", "book", "which", "is", "on", "the", "table", "is", "yours", "."], "The book which is on the table is yours .", "テーブルの上にある本はあなたのものです"],
    ["jhs3_relative", ["This", "is", "the", "book", "which", "I", "wrote", "."], "This is the book which I wrote .", "これは私が書いた本です (which)"],
    ["jhs3_relative", ["This", "is", "the", "movie", "which", "I", "saw", "yesterday", "."], "This is the movie which I saw yesterday .", "これは私が昨日見た映画です"],
    ["jhs3_relative", ["These", "are", "the", "cookies", "which", "my", "mother", "made", "."], "These are the cookies which my mother made .", "これらは私の母が作ったクッキーです"],
    ["jhs3_relative", ["This", "is", "the", "dog", "that", "I", "like", "the", "best", "."], "This is the dog that I like the best .", "これが私が一番好きな犬です"],

    // --- JHS 3: Indirect Question (indirect) ---
    ["jhs3_indirect", ["I", "do", "not", "know", "where", "he", "is", "."], "I do not know where he is .", "私は彼がどこにいるか知りません (where he is)"],
    ["jhs3_indirect", ["Do", "you", "know", "who", "she", "is", "?"], "Do you know who she is ?", "あなたは彼女が誰か知っていますか (who she is)"],
    ["jhs3_indirect", ["Please", "tell", "me", "what", "you", "want", "."], "Please tell me what you want .", "あなたが欲しいものを教えてください (what you want)"],
    ["jhs3_indirect", ["Tell", "me", "where", "you", "live", "."], "Tell me where you live .", "あなたがどこに住んでいるか教えて"],
    ["jhs3_indirect", ["I", "wonder", "why", "he", "is", "crying", "."], "I wonder why he is crying .", "なぜ彼は泣いているのだろう (I wonder ...)"],
    ["jhs3_indirect", ["I", "wonder", "when", "he", "will", "come", "."], "I wonder when he will come .", "彼はいつ来るのだろう"],

    // --- JHS 3: Subjunctive Past (subjunctive) ---
    ["jhs3_subjunctive", ["If", "I", "were", "a", "bird", ",", "I", "could", "fly", "."], "If I were a bird , I could fly .", "もし私が鳥なら、飛べるのに (If I were ...)"],
    ["jhs3_subjunctive", ["If", "I", "were", "a", "cat", ",", "I", "would", "sleep", "all", "day", "."], "If I were a cat , I would sleep all day .", "もし私が猫なら、一日中寝るのに"],
    ["jhs3_subjunctive", ["If", "I", "had", "money", ",", "I", "would", "buy", "it", "."], "If I had money , I would buy it .", "もしお金があれば、それを買うのに"],
    ["jhs3_subjunctive", ["If", "I", "had", "time", ",", "I", "would", "help", "you", "."], "If I had time , I would help you .", "もし時間があれば、あなたを手伝うのに"],
    ["jhs3_subjunctive", ["If", "it", "were", "sunny", ",", "we", "could", "go", "out", "."], "If it were sunny , we could go out .", "もし晴れていれば、出かけられるのに"],
    ["jhs3_subjunctive", ["If", "it", "were", "not", "raining", ",", "we", "could", "play", "soccer", "."], "If it were not raining , we could play soccer .", "もし雨が降っていなければ、サッカーができるのに"],
    ["jhs3_subjunctive", ["I", "wish", "I", "were", "rich", "."], "I wish I were rich .", "私が金持ちならいいのに (I wish ...)"],
    ["jhs3_subjunctive", ["I", "wish", "I", "were", "taller", "."], "I wish I were taller .", "私がもっと背が高ければいいのに"],
    ["jhs3_subjunctive", ["I", "wish", "I", "knew", "the", "answer", "."], "I wish I knew the answer .", "答えを知っていればいいのに"],
    ["jhs3_subjunctive", ["I", "wish", "I", "had", "a", "car", "."], "I wish I had a car .", "車があればいいのに"],
    ["jhs3_subjunctive", ["If", "I", "were", "you", ",", "I", "would", "not", "do", "that", "."], "If I were you , I would not do that .", "もし私があなたなら、そんなことはしません"],
    ["jhs3_subjunctive", ["If", "I", "were", "you", ",", "I", "would", "go", "there", "."], "If I were you , I would go there .", "もし私があなたなら、そこへ行くだろう"],
    ["jhs3_subjunctive", ["I", "wish", "I", "could", "speak", "English", "."], "I wish I could speak English .", "英語が話せたらいいのに"],
    ["jhs3_subjunctive", ["I", "wish", "I", "could", "fly", "."], "I wish I could fly .", "空を飛べたらいいのに"],

    // --- EXPANSION: JHS 1 General ---
    ["jhs1_general", ["I", "do", "not", "play", "tennis", "."], "I do not play tennis .", "私はテニスをしません"],
    ["jhs1_general", ["He", "does", "not", "play", "soccer", "."], "He does not play soccer .", "彼はサッカーをしません"],
    ["jhs1_general", ["Do", "you", "like", "music", "?"], "Do you like music ?", "あなたは音楽が好きですか"],
    ["jhs1_general", ["Does", "she", "study", "English", "?"], "Does she study English ?", "彼女は英語を勉強しますか"],
    ["jhs1_general", ["My", "mother", "cooks", "dinner", "."], "My mother cooks dinner .", "私の母は夕食を作ります"],
    ["jhs1_general", ["We", "want", "a", "new", "car", "."], "We want a new car .", "私たちは新しい車が欲しいです"],
    ["jhs1_general", ["Who", "eats", "natto", "?"], "Who eats natto ?", "誰が納豆を食べますか"],
    ["jhs1_general", ["What", "do", "they", "play", "?"], "What do they play ?", "彼らは何をしますか"],
    ["jhs1_general", ["Where", "do", "you", "go", "?"], "Where do you go ?", "あなたはどこへ行きますか"],
    ["jhs1_general", ["I", "watch", "TV", "every", "day", "."], "I watch TV every day .", "私は毎日テレビを見ます"],

    // --- EXPANSION: JHS 1 Can ---
    ["jhs1_can", ["I", "cannot", "swim", "fast", "."], "I cannot swim fast .", "私は速く泳げません"],
    ["jhs1_can", ["He", "cannot", "cook", "well", "."], "He cannot cook well .", "彼は上手に料理ができません"],
    ["jhs1_can", ["Can", "you", "speak", "Japanese", "?"], "Can you speak Japanese ?", "あなたは日本語を話せますか"],
    ["jhs1_can", ["Can", "she", "play", "tennis", "?"], "Can she play tennis ?", "彼女はテニスができますか"],
    ["jhs1_can", ["Can", "I", "eat", "this", "cake", "?"], "Can I eat this cake ?", "このケーキを食べてもいいですか"],
    ["jhs1_can", ["We", "can", "go", "there", "."], "We can go there .", "私たちはそこへ行けます"],
    ["jhs1_can", ["Who", "can", "run", "fast", "?"], "Who can run fast ?", "誰が速く走れますか"],
    ["jhs1_can", ["What", "can", "you", "do", "?"], "What can you do ?", "あなたは何ができますか"],
    ["jhs1_can", ["You", "can", "sing", "well", "."], "You can sing well .", "あなたは上手に歌えます"],

    // --- EXPANSION: JHS 1 Progressive ---
    ["jhs1_prog", ["I", "am", "not", "sleeping", "."], "I am not sleeping .", "私は眠っていません"],
    ["jhs1_prog", ["He", "is", "not", "watching", "TV", "."], "He is not watching TV .", "彼はテレビを見ていません"],
    ["jhs1_prog", ["Are", "you", "reading", "a", "book", "?"], "Are you reading a book ?", "あなたは本を読んでいますか"],
    ["jhs1_prog", ["Is", "she", "playing", "tennis", "?"], "Is she playing tennis ?", "彼女はテニスをしていますか"],
    ["jhs1_prog", ["What", "is", "he", "doing", "?"], "What is he doing ?", "彼は何をしているのですか"],
    ["jhs1_prog", ["Who", "is", "running", "?"], "Who is running ?", "誰が走っていますか"],
    ["jhs1_prog", ["They", "are", "eating", "dinner", "."], "They are eating dinner .", "彼らは夕食を食べています"],
    ["jhs1_prog", ["We", "are", "studying", "math", "now", "."], "We are studying math now .", "私たちは今数学を勉強しています"],
    ["jhs1_prog", ["The", "bird", "is", "flying", "."], "The bird is flying .", "鳥が飛んでいます"],

    // --- EXPANSION: JHS 1 Past ---
    ["jhs1_past", ["I", "did", "not", "go", "to", "school", "."], "I did not go to school .", "私は学校へ行きませんでした"],
    ["jhs1_past", ["He", "did", "not", "play", "tennis", "."], "He did not play tennis .", "彼はテニスをしませんでした"],
    ["jhs1_past", ["Did", "you", "watch", "the", "movie", "?"], "Did you watch the movie ?", "あなたはその映画を見ましたか"],
    ["jhs1_past", ["Did", "she", "cook", "dinner", "?"], "Did she cook dinner ?", "彼女は夕食を作りましたか"],
    ["jhs1_past", ["What", "did", "you", "buy", "?"], "What did you buy ?", "あなたは何を買いましたか"],
    ["jhs1_past", ["Who", "went", "there", "?"], "Who went there ?", "誰がそこへ行きましたか"],
    ["jhs1_past", ["We", "enjoyed", "music", "."], "We enjoyed music .", "私たちは音楽を楽しみました"],
    ["jhs1_past", ["I", "visited", "Kyoto", "yesterday", "."], "I visited Kyoto yesterday .", "私は昨日京都を訪れました"],
    ["jhs1_past", ["They", "came", "here", "."], "They came here .", "彼らはここに来ました"],

    // --- EXPANSION: JHS 2 Future ---
    ["jhs2_future", ["I", "will", "study", "English", "."], "I will study English .", "私は英語を勉強するつもりです"],
    ["jhs2_future", ["He", "will", "not", "come", "."], "He will not come .", "彼は来ないでしょう"],
    ["jhs2_future", ["Will", "it", "rain", "?"], "Will it rain ?", "雨は降るでしょうか"],
    ["jhs2_future", ["What", "will", "you", "do", "?"], "What will you do ?", "あなたは何をするつもりですか"],
    ["jhs2_future", ["I", "am", "going", "to", "play", "tennis", "."], "I am going to play tennis .", "私はテニスをする予定です (be going to)"],
    ["jhs2_future", ["She", "is", "not", "going", "to", "cook", "."], "She is not going to cook .", "彼女は料理をしない予定です"],
    ["jhs2_future", ["Are", "you", "going", "to", "leave", "?"], "Are you going to leave ?", "あなたは去るつもりですか"],
    ["jhs2_future", ["When", "will", "he", "arrive", "?"], "When will he arrive ?", "彼はいつ到着しますか"],

    // --- EXPANSION: JHS 2 Auxiliaries ---
    ["jhs2_aux", ["I", "must", "go", "home", "."], "I must go home .", "私は家に帰らなければなりません"],
    ["jhs2_aux", ["You", "must", "not", "eat", "here", "."], "You must not eat here .", "ここで食べてはいけません"],
    ["jhs2_aux", ["Do", "I", "have", "to", "answer", "?"], "Do I have to answer ?", "私は答えなければなりませんか"],
    ["jhs2_aux", ["She", "does", "not", "have", "to", "go", "."], "She does not have to go .", "彼女は行く必要はありません"],
    ["jhs2_aux", ["We", "should", "help", "him", "."], "We should help him .", "私たちは彼を助けるべきです"],
    ["jhs2_aux", ["You", "should", "not", "run", "."], "You should not run .", "あなたは走るべきではありません"],
    ["jhs2_aux", ["May", "I", "use", "your", "pen", "?"], "May I use your pen ?", "あなたのペンを使ってもいいですか"],
    ["jhs2_aux", ["Could", "you", "help", "me", "?"], "Could you help me ?", "手伝っていただけませんか"],
    ["jhs2_aux", ["Shall", "we", "start", "?"], "Shall we start ?", "始めましょうか"],

    // --- EXPANSION: JHS 2 Infinitive/Gerund ---
    ["jhs2_inf", ["I", "like", "to", "read", "books", "."], "I like to read books .", "私は本を読むのが好きです"],
    ["jhs2_inf", ["He", "started", "to", "cry", "."], "He started to cry .", "彼は泣き始めました"],
    ["jhs2_inf", ["I", "want", "to", "go", "to", "Kyoto", "."], "I want to go to Kyoto .", "私は京都に行きたいです"],
    ["jhs2_inf", ["To", "run", "is", "fun", "."], "To run is fun .", "走ることは楽しいです"],
    ["jhs2_inf", ["I", "am", "happy", "to", "see", "you", "."], "I am happy to see you .", "あなたに会えて幸せです"],
    ["jhs2_inf", ["I", "enjoy", "listening", "to", "music", "."], "I enjoy listening to music .", "私は音楽を聴くのを楽しみます"],
    ["jhs2_inf", ["He", "stopped", "smoking", "."], "He stopped smoking .", "彼はタバコをやめました"],
    ["jhs2_inf", ["She", "likes", "cooking", "."], "She likes cooking .", "彼女は料理が好きです"],
    ["jhs2_inf", ["Thank", "you", "for", "helping", "."], "Thank you for helping .", "手伝ってくれてありがとう"],

    // --- JHS 2 Comparison ---
    ["jhs2_comp", ["You", "are", "faster", "than", "me", "."], "You are faster than me .", "あなたは私より速いです"],
    ["jhs2_comp", ["Tokyo", "is", "larger", "than", "Osaka", "."], "Tokyo is larger than Osaka .", "東京は大阪より大きいです"],
    ["jhs2_comp", ["He", "is", "the", "fastest", "runner", "."], "He is the fastest runner .", "彼は最も速い走者です"],
    ["jhs2_comp", ["This", "is", "the", "oldest", "temple", "."], "This is the oldest temple .", "これは最も古い寺です"],
    ["jhs2_comp", ["Math", "is", "more", "difficult", "than", "English", "."], "Math is more difficult than English .", "数学は英語より難しいです"],
    ["jhs2_comp", ["This", "flower", "is", "the", "most", "beautiful", "."], "This flower is the most beautiful .", "この花は最も美しいです"],
    ["jhs2_comp", ["He", "is", "as", "tall", "as", "Ken", "."], "He is as tall as Ken .", "彼はケンと同じくらいの背の高さです"],
    ["jhs2_comp", ["I", "cannot", "run", "as", "fast", "as", "you", "."], "I cannot run as fast as you .", "私はあなたほど速く走れません"],
    ["jhs2_comp", ["Ken", "runs", "faster", "than", "any", "other", "boy", "in", "his", "class", "."], "Ken runs faster than any other boy in his class .", "ケンはクラスの他のどの男の子よりも速く走る"],
    ["jhs2_comp", ["Kyoto", "is", "one", "of", "the", "most", "beautiful", "cities", "in", "Japan", "."], "Kyoto is one of the most beautiful cities in Japan .", "京都は日本で最も美しい都市の一つです"],
    ["jhs2_comp", ["This", "peach", "is", "twice", "as", "expensive", "as", "that", "banana", "."], "This peach is twice as expensive as that banana .", "この桃はあのバナナの２倍高い"],
    ["jhs2_comp", ["Is", "Mary", "taller", "than", "Bob", "?"], "Is Mary taller than Bob ?", "メアリーはボブより背が高いですか？"],
    ["jhs2_comp", ["Can", "you", "swim", "faster", "than", "her", "?"], "Can you swim faster than her ?", "あなたは彼女より速く泳げますか？"],
    ["jhs2_comp", ["I", "like", "baseball", "better", "than", "soccer", "."], "I like baseball better than soccer .", "私はサッカーよりも野球が好きです"],
    ["jhs2_comp", ["He", "isn't", "as", "kind", "as", "Tom", "."], "He isn't as kind as Tom .", "彼はトムほど親切ではありません"],

    // --- JHS 2 Passive ---
    ["jhs2_passive", ["The", "window", "was", "opened", "by", "him", "."], "The window was opened by him .", "その窓は彼によって開けられました"],
    ["jhs2_passive", ["This", "picture", "was", "taken", "by", "her", "."], "This picture was taken by her .", "この写真は彼女によって撮られました"],
    ["jhs2_passive", ["English", "is", "studied", "by", "many", "students", "."], "English is studied by many students .", "英語は多くの生徒によって勉強されています"],
    ["jhs2_passive", ["This", "cake", "was", "made", "by", "my", "mother", "."], "This cake was made by my mother .", "このケーキは私の母によって作られました"],
    ["jhs2_passive", ["Was", "it", "made", "in", "China", "?"], "Was it made in China ?", "それは中国で作られましたか"],
    ["jhs2_passive", ["These", "books", "are", "not", "read", "by", "anyone", "."], "These books are not read by anyone .", "これらの本は誰にも読まれていません"],
    ["jhs2_passive", ["The", "car", "was", "washed", "by", "my", "father", "."], "The car was washed by my father .", "その車は私の父によって洗われました"],
    ["jhs2_passive", ["Is", "soccer", "played", "in", "America", "?"], "Is soccer played in America ?", "サッカーはアメリカでプレイされていますか"],

    // --- EXPANSION: JHS 3 Perfect ---
    ["jhs3_perfect", ["I", "have", "already", "finished", "it", "."], "I have already finished it .", "私はすでにそれを終えました"],
    ["jhs3_perfect", ["Have", "you", "eaten", "lunch", "yet", "?"], "Have you eaten lunch yet ?", "もう昼食を食べましたか"],
    ["jhs3_perfect", ["I", "have", "not", "seen", "him", "yet", "."], "I have not seen him yet .", "私はまだ彼に会っていません"],
    ["jhs3_perfect", ["She", "has", "lost", "her", "bag", "."], "She has lost her bag .", "彼女は鞄をなくしてしまいました"],
    ["jhs3_perfect", ["Have", "you", "ever", "eaten", "natto", "?"], "Have you ever eaten natto ?", "納豆を食べたことがありますか"],
    ["jhs3_perfect", ["I", "have", "visited", "Tokyo", "twice", "."], "I have visited Tokyo twice .", "私は2回東京を訪れました"],
    ["jhs3_perfect", ["He", "has", "lived", "in", "Japan", "for", "a", "long", "time", "."], "He has lived in Japan for a long time .", "彼は長い間日本に住んでいます"],
    ["jhs3_perfect", ["How", "long", "have", "you", "known", "her", "?"], "How long have you known her ?", "彼女と知り合ってどれくらいですか"],

    // --- EXPANSION: JHS 3 Participle ---
    ["jhs3_participle", ["The", "bird", "flying", "in", "the", "sky", "is", "big", "."], "The bird flying in the sky is big .", "空を飛んでいる鳥は大きいです"],
    ["jhs3_participle", ["I", "saw", "a", "boy", "running", "in", "the", "park", "."], "I saw a boy running in the park .", "私は公園で走っている少年を見ました"],
    ["jhs3_participle", ["Who", "is", "the", "man", "sleeping", "on", "the", "bench", "?"], "Who is the man sleeping on the bench ?", "ベンチで寝ている男性は誰ですか"],
    ["jhs3_participle", ["This", "is", "a", "book", "read", "by", "children", "."], "This is a book read by children .", "これは子供たちに読まれている本です"],
    ["jhs3_participle", ["I", "want", "a", "bag", "made", "in", "Italy", "."], "I want a bag made in Italy .", "私はイタリア製の鞄が欲しいです"],
    ["jhs3_participle", ["The", "language", "spoken", "in", "Brazil", "is", "Portuguese", "."], "The language spoken in Brazil is Portuguese .", "ブラジルで話されている言語はポルトガル語です"],
    ["jhs3_participle", ["Look", "at", "the", "broken", "window", "."], "Look at the broken window .", "割れた窓を見て"],

    // --- EXPANSION: JHS 3 Relative ---
    ["jhs3_relative", ["I", "have", "a", "friend", "who", "speaks", "French", "."], "I have a friend who speaks French .", "私にはフランス語を話す友達がいます"],
    ["jhs3_relative", ["The", "girl", "who", "is", "playing", "tennis", "is", "Yumi", "."], "The girl who is playing tennis is Yumi .", "テニスをしている少女はユミです"],
    ["jhs3_relative", ["Do", "you", "know", "the", "man", "who", "came", "here", "?"], "Do you know the man who came here ?", "ここに来た男性を知っていますか"],
    ["jhs3_relative", ["This", "is", "a", "book", "which", "is", "popular", "among", "them", "."], "This is a book which is popular among them .", "これは彼らの間で人気のある本です"],
    ["jhs3_relative", ["The", "movie", "which", "I", "watched", "last", "night", "was", "fun", "."], "The movie which I watched last night was fun .", "私が昨夜見た映画は楽しかった"],
    ["jhs3_relative", ["There", "is", "a", "cat", "that", "is", "sleeping", "on", "the", "desk", "."], "There is a cat that is sleeping on the desk .", "机の上で眠っている猫がいます"],
    ["jhs3_relative", ["This", "is", "the", "only", "thing", "that", "I", "need", "."], "This is the only thing that I need .", "これは私が必要な唯一のものです"],

    // --- EXPANSION: JHS 3 Indirect Question ---
    ["jhs3_indirect", ["I", "know", "what", "he", "likes", "."], "I know what he likes .", "私は彼が何が好きか知っています"],
    ["jhs3_indirect", ["Do", "you", "know", "where", "she", "went", "?"], "Do you know where she went ?", "彼女がどこへ行ったか知っていますか"],
    ["jhs3_indirect", ["Please", "tell", "me", "when", "it", "starts", "."], "Please tell me when it starts .", "いつ始まるか教えてください"],
    ["jhs3_indirect", ["I", "wonder", "who", "made", "this", "."], "I wonder who made this .", "誰がこれを作ったのだろう"],
    ["jhs3_indirect", ["He", "asked", "me", "where", "I", "lived", "."], "He asked me where I lived .", "彼は私がどこに住んでいるか尋ねました"],
    ["jhs3_indirect", ["I", "do", "not", "know", "why", "he", "is", "angry", "."], "I do not know why he is angry .", "なぜ彼が怒っているのか分かりません"],
    ["jhs3_indirect", ["You", "are", "from", "Canada", ",", "aren't", "you", "?"], "You are from Canada , aren't you ?", "あなたはカナダ出身ですよね (付加疑問)"],
    ["jhs3_indirect", ["It", "is", "hot", "today", ",", "isn't", "it", "?"], "It is hot today , isn't it ?", "今日は暑いですよね (付加疑問)"],
    ["jhs3_indirect", ["Ken", "likes", "soccer", ",", "doesn't", "he", "?"], "Ken likes soccer , doesn't he ?", "ケンはサッカーが好きですよね (付加疑問)"],
    ["jhs3_indirect", ["You", "don't", "play", "tennis", ",", "do", "you", "?"], "You don't play tennis , do you ?", "あなたはテニスをしませんよね (付加疑問)"],
    ["jhs3_indirect", ["Mary", "can", "speak", "Japanese", ",", "can't", "she", "?"], "Mary can speak Japanese , can't she ?", "メアリーは日本語を話せますよね (付加疑問)"],

    // --- EXPANSION: JHS 3 Subjunctive ---
    ["jhs3_subjunctive", ["If", "I", "were", "you", ",", "I", "would", "buy", "this", "."], "If I were you , I would buy this .", "私があなたなら、これを買うだろう"],
    ["jhs3_subjunctive", ["If", "I", "could", "swim", ",", "I", "would", "go", "to", "the", "sea", "."], "If I could swim , I would go to the sea .", "泳げるなら、海へ行くのに"],
    ["jhs3_subjunctive", ["I", "wish", "I", "were", "a", "good", "singer", "."], "I wish I were a good singer .", "私が上手な歌手ならいいのに"],
    ["jhs3_subjunctive", ["I", "wish", "it", "were", "Sunday", "."], "I wish it were Sunday .", "日曜日ならいいのに"],
    ["jhs3_subjunctive", ["If", "I", "had", "a", "bike", ",", "I", "could", "go", "there", "."], "If I had a bike , I could go there .", "自転車があれば、そこへ行けるのに"],

    // --- EXPANSION: JHS 1 Imperative (imperative) ---
    ["jhs1_imperative", ["Look", "at", "this", "picture", "."], "Look at this picture .", "この写真を見なさい"],
    ["jhs1_imperative", ["Be", "kind", "to", "him", "."], "Be kind to him .", "彼に親切にしなさい"],
    ["jhs1_imperative", ["Be", "careful", "."], "Be careful .", "気を付けて"],
    ["jhs1_imperative", ["Clean", "your", "room", "."], "Clean your room .", "部屋を掃除しなさい"],
    ["jhs1_imperative", ["Open", "the", "window", "."], "Open the window .", "窓を開けて"],
    ["jhs1_imperative", ["Let's", "play", "baseball", "together", "."], "Let's play baseball together .", "一緒に野球をしよう"],
    ["jhs1_imperative", ["Let's", "study", "English", "with", "them", "."], "Let's study English with them .", "彼らと一緒に英語を勉強しましょう"],
    ["jhs1_imperative", ["Please", "sit", "down", "."], "Please sit down .", "座ってください"],
    ["jhs1_imperative", ["Close", "the", "door", ",", "please", "."], "Close the door , please .", "ドアを閉めてください"],
    ["jhs1_imperative", ["Don't", "run", "in", "the", "classroom", "."], "Don't run in the classroom .", "教室で走らないで"],
    ["jhs1_imperative", ["Be", "quiet", "."], "Be quiet .", "静かにして"],
    ["jhs1_imperative", ["Don't", "be", "so", "noisy", "."], "Don't be so noisy .", "うるさくするな"],

    // --- EXPANSION: JHS 1 Interrogative (interrogative) ---
    ["jhs1_interrogative", ["What", "animals", "do", "you", "like", "?"], "What animals do you like ?", "何の動物が好きですか？"],
    ["jhs1_interrogative", ["What", "sports", "do", "you", "play", "?"], "What sports do you play ?", "どんなスポーツをしますか？"],
    ["jhs1_interrogative", ["How", "many", "cats", "do", "you", "have", "?"], "How many cats do you have ?", "何匹の猫を飼っていますか？"],
    ["jhs1_interrogative", ["How", "much", "is", "it", "?"], "How much is it ?", "これはおいくらですか？"],
    ["jhs1_interrogative", ["Which", "do", "you", "like", ",", "curry", "or", "pasta", "?"], "Which do you like , curry or pasta ?", "カレーとパスタ、どちらが好きですか？"],
    ["jhs1_interrogative", ["How", "far", "is", "it", "to", "the", "station", "?"], "How far is it to the station ?", "駅までどれくらいの距離がありますか？"],
    ["jhs1_interrogative", ["How", "do", "you", "go", "to", "school", "?"], "How do you go to school ?", "どうやって学校に行きますか？"],
    ["jhs1_interrogative", ["Why", "are", "you", "sad", "?"], "Why are you sad ?", "なぜ悲しいんですか？"],
    ["jhs1_interrogative", ["Whose", "book", "is", "this", "?"], "Whose book is this ?", "これは誰の本ですか？"],
    ["jhs1_interrogative", ["Whose", "is", "this", "bag", "?"], "Whose is this bag ?", "このかばんは誰のものですか？"],

    // --- EXPANSION: JHS 2 SVOO/SVOC (svoo) ---
    ["jhs2_svoo", ["My", "father", "gave", "me", "a", "pen", "."], "My father gave me a pen .", "父は私にペンをくれました"],
    ["jhs2_svoo", ["My", "mother", "cooked", "me", "a", "cake", "."], "My mother cooked me a cake .", "母は私にケーキを作ってくれました"],
    ["jhs2_svoo", ["I", "told", "him", "the", "truth", "."], "I told him the truth .", "私は彼に真実を告げました"],
    ["jhs2_svoo", ["I", "will", "show", "her", "the", "picture", "."], "I will show her the picture .", "私は彼女にその写真を見せるつもりです"],
    ["jhs2_svoo", ["He", "teaches", "English", "to", "my", "brother", "."], "He teaches English to my brother .", "彼は私の弟に英語を教えます"],
    ["jhs2_svoo", ["Tom", "bought", "a", "present", "for", "Yumi", "."], "Tom bought a present for Yumi .", "トムはユミのためにプレゼントを買いました"],
    ["jhs2_svoo", ["The", "story", "made", "me", "sad", "."], "The story made me sad .", "その話は私を悲しくさせました"],
    ["jhs2_svoo", ["Ken", "always", "makes", "her", "happy", "."], "Ken always makes her happy .", "ケンはいつも彼女を幸せにします"],
    ["jhs2_svoo", ["We", "call", "him", "Bob", "."], "We call him Bob .", "私たちは彼をボブと呼びます"],
    ["jhs2_svoo", ["He", "named", "his", "cat", "Tama", "."], "He named his cat Tama .", "彼は猫にタマと名付けました"],
    ["jhs2_svoo", ["Keep", "the", "door", "open", "."], "Keep the door open .", "ドアを開けたままにしておいて"],
    ["jhs2_svoo", ["Don't", "keep", "the", "window", "closed", "."], "Don't keep the window closed .", "窓を閉めっぱなしにしないで"],

    // --- EXPANSION: JHS 2 Conjunctions (conjunction) ---
    ["jhs2_conjunction", ["I", "read", "books", "when", "it", "rains", "."], "I read books when it rains .", "私は雨が降っているとき、本を読みます"],
    ["jhs2_conjunction", ["When", "he", "is", "at", "school", ",", "he", "usually", "studies", "hard", "."], "When he is at school , he usually studies hard .", "彼は学校にいるとき、たいてい一生懸命勉強します"],
    ["jhs2_conjunction", ["We", "will", "swim", "in", "the", "sea", "if", "it", "is", "fine", "tomorrow", "."], "We will swim in the sea if it is fine tomorrow .", "もし明日晴れたら、私たちは海で泳ぐつもりです"],
    ["jhs2_conjunction", ["If", "it", "is", "rainy", "tomorrow", ",", "I", "will", "not", "go", "shopping", "."], "If it is rainy tomorrow , I will not go shopping .", "もし明日雨なら、私は買い物にいきません"],
    ["jhs2_conjunction", ["I", "think", "that", "he", "went", "to", "school", "."], "I think that he went to school .", "私は彼が学校に行ったと思います"],
    ["jhs2_conjunction", ["Do", "you", "think", "that", "Yumi", "was", "happy", "then", "?"], "Do you think that Yumi was happy then ?", "あなたはユミがあのとき幸せだったと思いますか？"],
    ["jhs2_conjunction", ["He", "was", "absent", "from", "school", "because", "he", "was", "sick", "."], "He was absent from school because he was sick .", "彼は病気だったので、学校を休みました"],
    ["jhs2_conjunction", ["Because", "Ken", "was", "very", "busy", ",", "he", "didn't", "eat", "lunch", "."], "Because Ken was very busy , he didn't eat lunch .", "ケンはとても忙しかったので、昼食を食べませんでした"],
    ["jhs2_conjunction", ["I", "stayed", "home", "because", "it", "was", "snowing", "."], "I stayed home because it was snowing .", "雪が降っていたので、家にいました"],
    ["jhs2_conjunction", ["I", "hope", "that", "it", "will", "be", "sunny", "tomorrow", "."], "I hope that it will be sunny tomorrow .", "明日が晴れることを願っています"],
    ["jhs2_conjunction", ["My", "mother", "knows", "that", "I", "cried", "yesterday", "."], "My mother knows that I cried yesterday .", "私の母は私が昨日泣いたことを知っています"],

    // --- EXPANSION: JHS 3 Causative (causative) ---
    ["jhs3_causative", ["My", "mother", "makes", "my", "sister", "clean", "her", "room", "."], "My mother makes my sister clean her room .", "私の母は、私の妹に部屋を掃除させます"],
    ["jhs3_causative", ["My", "father", "let", "me", "play", "baseball", "with", "them", "."], "My father let me play baseball with them .", "父は私に彼らと野球をすることを許しました"],
    ["jhs3_causative", ["I", "had", "her", "close", "the", "door", "."], "I had her close the door .", "私は彼女にドアを閉めてもらいました"],
    ["jhs3_causative", ["Tom", "will", "have", "them", "help", "him", "."], "Tom will have them help him .", "トムは彼らに手伝ってもらうでしょう"],
    ["jhs3_causative", ["Please", "let", "me", "know", "."], "Please let me know .", "私に知らせてください"],
    ["jhs3_causative", ["My", "teacher", "made", "us", "practice", "soccer", "."], "My teacher made us practice soccer .", "先生は私たちにサッカーの練習をさせた"],
    ["jhs3_causative", ["The", "movie", "made", "them", "cry", "."], "The movie made them cry .", "その映画は彼らを泣かせました"],
    ["jhs3_causative", ["Did", "she", "make", "you", "study", "math", "?"], "Did she make you study math ?", "彼女はあなたに数学の勉強をさせましたか？"],
    ["jhs3_causative", ["Did", "Mr.", "Brown", "have", "her", "play", "the", "piano", "?"], "Did Mr. Brown have her play the piano ?", "ブラウン先生は彼女にピアノを弾かせましたか？"],
    ["jhs3_causative", ["I", "had", "the", "doctor", "look", "at", "my", "arm", "yesterday", "."], "I had the doctor look at my arm yesterday .", "私は昨日、お医者さんに腕を診てもらいました"],

    // --- EXPANSION: JHS 3 It is ... for ... to ... (it_for_to) ---
    ["jhs3_it_for_to", ["It", "is", "fun", "for", "us", "to", "learn", "English", "."], "It is fun for us to learn English .", "僕たちにとって、英語を学ぶことは楽しい"],
    ["jhs3_it_for_to", ["Is", "it", "important", "for", "you", "to", "play", "the", "guitar", "?"], "Is it important for you to play the guitar ?", "あなたにとってギターを弾くことは重要ですか？"],
    ["jhs3_it_for_to", ["It", "is", "interesting", "to", "read", "books", "."], "It is interesting to read books .", "本を読むのは面白いです"],
    ["jhs3_it_for_to", ["It", "is", "difficult", "for", "Ken", "to", "swim", "fast", "."], "It is difficult for Ken to swim fast .", "ケンにとって速く泳ぐことは難しい"],
    ["jhs3_it_for_to", ["Was", "it", "necessary", "for", "me", "to", "practice", "baseball", "more", "?"], "Was it necessary for me to practice baseball more ?", "私は野球をもっと練習する必要がありましたか？"],
    ["jhs3_it_for_to", ["It", "is", "easy", "for", "my", "sister", "to", "read", "this", "book", "."], "It is easy for my sister to read this book .", "私の妹にとってこの本を読むことは簡単だ"],
    ["jhs3_it_for_to", ["It", "is", "happy", "for", "Bob", "to", "sleep", "."], "It is happy for Bob to sleep .", "ボブにとって、眠ることは幸せです"],
    ["jhs3_it_for_to", ["It", "is", "important", "for", "children", "to", "play", "outside", "."], "It is important for children to play outside .", "子供たちにとって、外で遊ぶことは重要だ"],
    ["jhs3_it_for_to", ["It", "is", "wonderful", "to", "be", "kind", "to", "someone", "."], "It is wonderful to be kind to someone .", "誰かに優しくすることは素晴らしいです"],
    ["jhs3_it_for_to", ["Is", "it", "difficult", "for", "them", "to", "travel", "abroad", "?"], "Is it difficult for them to travel abroad ?", "彼らにとって旅行に行くことは難しいですか？"],

    // --- EXPANSION: JHS 1 Imperative (imperative) ---
    ["jhs1_imperative", ["Wash", "your", "hands", "before", "dinner", "."], "Wash your hands before dinner .", "夕食の前に手を洗いなさい"],
    ["jhs1_imperative", ["Let's", "take", "a", "picture", "here", "."], "Let's take a picture here .", "ここで写真を撮りましょう"],
    ["jhs1_imperative", ["Don't", "play", "games", "all", "night", "."], "Don't play games all night .", "一晩中ゲームをしてはいけません"],
    ["jhs1_imperative", ["Show", "me", "your", "notebook", ",", "please", "."], "Show me your notebook , please .", "あなたのノートを見せてください"],
    ["jhs1_imperative", ["Wait", "for", "me", "."], "Wait for me .", "私を待って"],
    ["jhs1_imperative", ["Don't", "eat", "too", "much", "."], "Don't eat too much .", "食べすぎないで"],
    ["jhs1_imperative", ["Help", "your", "mother", "."], "Help your mother .", "お母さんを手伝いなさい"],
    // --- EXPANSION: JHS 1 Interrogative (interrogative) ---
    ["jhs1_interrogative", ["How", "many", "books", "do", "you", "read", "?"], "How many books do you read ?", "何冊の本を読みますか？"],
    ["jhs1_interrogative", ["How", "many", "brothers", "do", "you", "have", "?"], "How many brothers do you have ?", "何人兄弟がいますか？"],
    ["jhs1_interrogative", ["How", "long", "is", "this", "movie", "?"], "How long is this movie ?", "この映画はどのくらいの長さですか？"],
    ["jhs1_interrogative", ["How", "long", "did", "you", "stay", "there", "?"], "How long did you stay there ?", "そこにどのくらい長く滞在しましたか？"],
    ["jhs1_interrogative", ["What", "time", "is", "it", "now", "?"], "What time is it now ?", "今は何時ですか？"],
    ["jhs1_interrogative", ["What", "time", "do", "you", "usually", "get", "up", "?"], "What time do you usually get up ?", "あなたはたいてい何時に起きますか？"],
    ["jhs1_interrogative", ["Which", "pen", "is", "yours", "?"], "Which pen is yours ?", "どちらのペンがあなたのものですか？"],
    ["jhs1_interrogative", ["When", "is", "your", "birthday", "?"], "When is your birthday ?", "あなたの誕生日はいつですか？"],
    // --- EXPANSION: JHS 2 Conjunctions (conjunction) ---
    ["jhs2_conjunction", ["I", "know", "that", "she", "is", "busy", "."], "I know that she is busy .", "彼女が忙しいことを私は知っています"],
    ["jhs2_conjunction", ["He", "said", "that", "he", "was", "tired", "."], "He said that he was tired .", "彼は疲れていると言いました"],
    ["jhs2_conjunction", ["Did", "you", "know", "that", "Ken", "likes", "music", "?"], "Did you know that Ken likes music ?", "ケンが音楽を好きだということを知っていましたか？"],
    ["jhs2_conjunction", ["I", "am", "sure", "that", "you", "will", "pass", "the", "exam", "."], "I am sure that you will pass the exam .", "あなたが試験に合格すると私は確信しています"],
    ["jhs2_conjunction", ["I", "hope", "that", "you", "can", "come", "to", "my", "party", "."], "I hope that you can come to my party .", "私のパーティーにあなたが来られることを願っています"],
    ["jhs2_conjunction", ["She", "thinks", "that", "this", "book", "is", "interesting", "."], "She thinks that this book is interesting .", "彼女はこの本が面白いと思っています"],
    ["jhs2_conjunction", ["I", "believe", "that", "he", "is", "a", "good", "doctor", "."], "I believe that he is a good doctor .", "私は彼が良い医者だと信じています"],
    // --- EXPANSION: JHS 3 Relative (relative) ---
    ["jhs3_relative", ["The", "girl", "who", "is", "reading", "a", "book", "is", "Yumi", "."], "The girl who is reading a book is Yumi .", "本を読んでいる少女はユミです"],
    ["jhs3_relative", ["I", "want", "to", "buy", "a", "car", "that", "is", "fast", "."], "I want to buy a car that is fast .", "私は速い車を買いたいです"],
    ["jhs3_relative", ["This", "is", "a", "movie", "which", "makes", "people", "happy", "."], "This is a movie which makes people happy .", "これは人々を幸せにする映画です"],
    ["jhs3_relative", ["Is", "there", "anything", "that", "I", "can", "do", "?"], "Is there anything that I can do ?", "私ができることは何かありますか？"],
    ["jhs3_relative", ["The", "man", "that", "I", "met", "yesterday", "is", "her", "father", "."], "The man that I met yesterday is her father .", "私が昨日会った男性は彼女の父親です"],
    ["jhs3_relative", ["This", "is", "the", "computer", "which", "I", "use", "every", "day", "."], "This is the computer which I use every day .", "これは私が毎日使っているコンピューターです"],
    ["jhs3_relative", ["A", "dictionary", "is", "a", "book", "which", "gives", "us", "the", "meanings", "of", "words", "."], "A dictionary is a book which gives us the meanings of words .", "辞書とは単語の意味を私たちに与える本です"],
    // --- EXPANSION: JHS 3 Indirect Question (indirect) ---
    ["jhs3_indirect", ["Do", "you", "know", "what", "time", "it", "is", "?"], "Do you know what time it is ?", "何時か知っていますか？"],
    ["jhs3_indirect", ["Can", "you", "tell", "me", "how", "old", "he", "is", "?"], "Can you tell me how old he is ?", "彼が何歳か教えてくれませんか？"],
    ["jhs3_indirect", ["I", "don't", "know", "who", "broke", "the", "window", "."], "I don't know who broke the window .", "誰が窓を割ったのかわかりません"],
    ["jhs3_indirect", ["He", "asked", "me", "why", "I", "was", "late", "."], "He asked me why I was late .", "彼はなぜ私が遅れたのか尋ねました"],
    ["jhs3_indirect", ["I", "wonder", "where", "she", "lives", "."], "I wonder where she lives .", "彼女はどこに住んでいるのだろう"],
    ["jhs3_indirect", ["Do", "you", "know", "what", "this", "means", "?"], "Do you know what this means ?", "これが何を意味するかわかりますか？"],
    // --- EXPANSION: JHS 3 Causative (causative) ---
    ["jhs3_causative", ["His", "words", "made", "me", "happy", "."], "His words made me happy .", "彼の言葉は私を嬉しくさせた"],
    ["jhs3_causative", ["This", "song", "makes", "me", "sad", "."], "This song makes me sad .", "この歌は私を悲しくさせます"],
    ["jhs3_causative", ["I", "will", "let", "you", "use", "my", "bike", "."], "I will let you use my bike .", "私の自転車を使わせてあげましょう"],
    ["jhs3_causative", ["She", "had", "her", "brother", "fix", "her", "computer", "."], "She had her brother fix her computer .", "彼女は弟にコンピューターを直してもらった"],
    ["jhs3_causative", ["The", "teacher", "made", "him", "clean", "the", "room", "."], "The teacher made him clean the room .", "先生は彼に部屋を掃除させた"],
    ["jhs3_causative", ["My", "father", "doesn't", "let", "me", "watch", "TV", "late", "at", "night", "."], "My father doesn't let me watch TV late at night .", "父は夜遅くに私にテレビを見させてくれません"],
    ["jhs3_causative", ["We", "had", "the", "waiter", "bring", "some", "water", "."], "We had the waiter bring some water .", "私たちはウェイターに水を持ってきてもらった"]
];

const QUESTION_DATA = RAW_DATA.map(item => ({
    unit: item[0],
    sentenceParts: item[1],
    correctOrder: item[2].split(" "),
    explanation: item[3]
}));
